# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL_kYQ3GlKg6ZmOzQVPm3wLNPAUZSANK
"""

!pip install mtcnn

!pip install deepface
from deepface import DeepFace
model = DeepFace.build_model("Facenet")

from google.colab import files
uploaded = files.upload()

img_path = list(uploaded.keys())[0]
print("Uploaded:", img_path)

from deepface import DeepFace
import cv2
import numpy as np
import matplotlib.pyplot as plt

def extract_face(img_path):

    faces = DeepFace.extract_faces(
        img_path = img_path,
        detector_backend = "mtcnn",
        enforce_detection = True)


    face = faces[0]["face"]
    face = (face * 255).astype("uint8")

    face = cv2.resize(face, (160, 160))

    return face

face = extract_face(img_path)
plt.imshow(face)
plt.axis("off")
plt.show()

from deepface import DeepFace
import cv2
import numpy as np
import matplotlib.pyplot as plt

from deepface import DeepFace
import numpy as np

detectors = ["mtcnn", "retinaface", "opencv"]

embedding = None

for detector in detectors:
    try:
        embedding = DeepFace.represent(
            img_path=img_path,
            model_name="Facenet",
            detector_backend=detector,
            enforce_detection=True
        )[0]["embedding"]
        print(f"Face detected using {detector}!")
        break  # stop at the first successful detector
    except Exception as e:
        print(f"{detector} failed: {e}")

if embedding is None:
    print("❌ All detectors failed to detect a face")
else:
    print("Embedding shape:", np.array(embedding).shape)
    print("First 5 values:", embedding[:5])

from deepface import DeepFace
from numpy import dot
from numpy.linalg import norm
from google.colab import files
import numpy as np

def cosine_similarity(emb1, emb2):
    return dot(emb1, emb2) / (norm(emb1) * norm(emb2))

def get_embedding(img_path, model_name="Facenet"):
    detectors = ["mtcnn", "retinaface", "opencv"]
    embedding = None
    for detector in detectors:
        try:
            embedding = DeepFace.represent(
                img_path=img_path,
                model_name=model_name,
                detector_backend=detector,
                enforce_detection=True
            )[0]["embedding"]
            print(f"✅ Face detected in {img_path} using {detector}")
            break
        except Exception as e:
            print(f"❌ {detector} failed for {img_path}: {e}")
    if embedding is None:
        print(f"❌ All detectors failed for {img_path}")
    return embedding

img1_path = img_path
embedding1 = get_embedding(img1_path)
if embedding1 is None:
    raise ValueError(f"Face could not be detected in {img1_path}")

uploaded = files.upload()
img2_path = list(uploaded.keys())[0]
embedding2 = get_embedding(img2_path)
if embedding2 is None:
    raise ValueError(f"Face could not be detected in {img2_path}")

similarity = cosine_similarity(embedding1, embedding2)
print("Cosine similarity:", similarity)

if similarity > 0.2:
    print("✅ Same person")
else:
    print("❌ Different person")